### ISSUE TITLE
Funktioniert nicht mit Meross MOD100

### ISSUE THREAD

**Issue by TTBerlin** [Apollon77/meross-cloud#102]
Funktioniert leider nicht mit dem Essential Oil Diffuser MOD100. Es werden nur die Datenpunkte online und connection (beide true) angelegt, mehr nicht.

**Comment by Apollon77** [comment]
This seems to be a new device. Then switch to debug log please and provide full log from adapter start.
ALso controll all relevant functions that are possible cia the meross app (turn on off, or whatever other functions are possible) and tell me the time when you did what and the order, so that I can match that to the logfile. also make some pauses maybe to have some separation between different functions.

Copy log from logfile on disk /opt/iobroker/log and not from admin. If you are curious about data send via email to iobroker@fischer-ka.de with reference to this issue.

**Comment by TTBerlin** [comment]
Ok...thank you!! I will send you the log via email!
Regards Thomas

**Comment by Apollon77** [comment]
See email ...
